version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    container_name: example-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:4.1.0
    container_name: example-kafka
    ports:
      - 29092:29092
      - 29093:29093
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: example-zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL://:29092,INTERNAL://:29093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:29092,INTERNAL://example-kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: example-es
    restart: always
    environment:
      - cluster.name=example-es
      - action.auto_create_index=false
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200

  mysql:
    image: percona:5.7.21
    container_name: example-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306

  redis:
    image: redis:5.0.7
    container_name: example-redis
    ports:
      - 6379:6379

  monitor:
    image: whalewatcher:latest
    container_name: example-monitor
    ports:
      - 8080:8080
    command: ["/bin/sleep", "1"] #["/bin/whalewatcher", "--config-var", "MONITOR_CONFIG"]
    environment:
      - MONITOR_CONFIG="
apps:
  elasticsearch:
    path:
    pattern:
  redis:
    path:
    pattern:
  mysql:
    path:
    pattern:
  kafka:
    path:
    patterm:
  zookeeper:
    path:
    pattern:
"
